# Generated by Django 3.1.7 on 2021-05-14 18:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models
import shop.validators


class Migration(migrations.Migration):

    replaces = [
        ("shop", "0001_initial"),
        ("shop", "0002_auto_20210209_0521"),
        ("shop", "0003_auto_20210209_0620"),
        ("shop", "0004_auto_20210209_1957"),
        ("shop", "0005_auto_20210210_1706"),
        ("shop", "0006_address_contactnumber"),
        ("shop", "0007_auto_20210213_1341"),
        ("shop", "0008_product_recommendations"),
        ("shop", "0009_auto_20210213_1421"),
        ("shop", "0010_auto_20210213_1423"),
        ("shop", "0011_order_order_number"),
        ("shop", "0012_auto_20210215_0549"),
        ("shop", "0013_orderproduct_session_id"),
        ("shop", "0014_auto_20210215_1848"),
        ("shop", "0015_auto_20210215_1849"),
        ("shop", "0016_auto_20210217_0640"),
        ("shop", "0017_orderproduct_created_at"),
        ("shop", "0018_auto_20210219_1647"),
        ("shop", "0019_auto_20210219_1649"),
        ("shop", "0020_auto_20210219_1651"),
        ("shop", "0021_auto_20210310_0819"),
        ("shop", "0022_auto_20210313_2036"),
        ("shop", "0023_product_iiko_id"),
        ("shop", "0024_authcode"),
        ("shop", "0025_auto_20210322_1948"),
        ("shop", "0026_user_birthday"),
        ("shop", "0027_auto_20210323_0856"),
        ("shop", "0028_merge_20210323_1049"),
        ("shop", "0029_auto_20210323_2150"),
        ("shop", "0030_auto_20210324_2220"),
        ("shop", "0031_auto_20210325_2117"),
        ("shop", "0032_auto_20210328_1455"),
    ]

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        blank=True,
                        max_length=31,
                        null=True,
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="День рождения"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        max_length=31, verbose_name="Номер телефона"
                    ),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Почта")),
                ("birth", models.DateField(verbose_name="Дата рождения")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Имя заказчика"),
                ),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        max_length=31, verbose_name="Номер телефона"
                    ),
                ),
                ("address", models.TextField(max_length=150, verbose_name="Адрес")),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("cash", "Наличными"), ("card", "Картой на сайте")],
                        max_length=100,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        default="", max_length=50, verbose_name="Номер заказа"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        default="xer8z99g7zpgu8qdm8lc5ods7822z047",
                        max_length=100,
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "article",
                    models.CharField(
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Артикул",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "price_discounted",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена после скидки",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(verbose_name="Доступное количество"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "filling",
                    models.TextField(blank=True, null=True, verbose_name="Начинка"),
                ),
                (
                    "topping",
                    models.TextField(blank=True, null=True, verbose_name="Декор"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "recommendations",
                    models.ManyToManyField(blank=True, to="shop.Product"),
                ),
                (
                    "iiko_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID IIKO",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="PromotedProductsSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("manual", "ручной"), ("auto", "автоматичесский")],
                        max_length=100,
                        verbose_name="Режим",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Заголовок промо"),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("week_this", "эта неделя"),
                            ("week_last", "прошлая неделя"),
                            ("month_this", "этот месяц"),
                            ("month_last", "прошлый месяц"),
                            ("year_half_this", "последние пол года"),
                            ("year_this", "текущий год"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Промежуток времени",
                    ),
                ),
                (
                    "limit",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальное количество товаров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка промо",
                "verbose_name_plural": "Настройки промо",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "work_hours",
                    models.CharField(max_length=50, verbose_name="Время работы"),
                ),
                (
                    "coordinates",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[shop.validators.is_coordinates],
                        verbose_name="Координаты",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Точка", max_length=255, verbose_name="Название точки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
        migrations.CreateModel(
            name="CartProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(default=1, verbose_name="Количество продукта"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=100, null=True, verbose_name="Сессия"),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзины",
            },
        ),
        migrations.CreateModel(
            name="ContactNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    phone_field.models.PhoneField(
                        blank=True,
                        max_length=31,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телефон",
                "verbose_name_plural": "Телефоны",
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество продукта"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="shop.order"
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        default="", max_length=100, verbose_name="Артикул"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        default=django.utils.timezone.now,
                        verbose_name="Дата покупки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт из заказа",
                "verbose_name_plural": "Продукты из заказа",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="image/product/", verbose_name="Картинка"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка продукта",
                "verbose_name_plural": "Картинки продуктов",
            },
        ),
        migrations.CreateModel(
            name="PromotedProductsManual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Приоритет"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
                (
                    "promoted",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.promotedproductssettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промо ручная настройка",
                "verbose_name_plural": "Промо ручная настройка",
            },
        ),
        migrations.CreateModel(
            name="FooterSocial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.CharField(max_length=255, verbose_name="Ссылка на соцсеть"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("instagram", "Инстаграмм"),
                            ("facebook", "Фейсбук"),
                            ("tiktok", "Тикток"),
                            ("youtube", "Ютуб"),
                            ("vk", "Вконтакте"),
                            ("google_play", "Google Play"),
                            ("app_store", "Apple Store"),
                        ],
                        max_length=255,
                        unique=True,
                        verbose_name="Соцсеть",
                    ),
                ),
            ],
            options={
                "verbose_name": "Соцсеть",
                "verbose_name_plural": "Соцсети",
            },
        ),
        migrations.CreateModel(
            name="CakeDecor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="image/cake/", verbose_name="Картинка"),
                ),
            ],
            options={
                "verbose_name": "Торт на заказ декор",
                "verbose_name_plural": "Торт на заказ (декор)",
            },
        ),
        migrations.CreateModel(
            name="CakePostcard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="image/cake/", verbose_name="Картинка"),
                ),
            ],
            options={
                "verbose_name": "Торт на заказ открытка",
                "verbose_name_plural": "Торт на заказ (открытка)",
            },
        ),
        migrations.CreateModel(
            name="CakeDesign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="image/cake/", verbose_name="Картинка"),
                ),
            ],
            options={
                "verbose_name": "Торт на заказ дизайн",
                "verbose_name_plural": "Торт на заказ (дизайн)",
            },
        ),
        migrations.CreateModel(
            name="CakeTopping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="image/cake/", verbose_name="Картинка"),
                ),
            ],
            options={
                "verbose_name": "Торт на заказ начинка",
                "verbose_name_plural": "Торт на заказ (начинка)",
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Заголовок"
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Текст")),
                (
                    "image",
                    models.ImageField(
                        upload_to="image/product/", verbose_name="Картинка"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ссылка на кноке",
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(unique=True, verbose_name="Приоритет"),
                ),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
            },
        ),
        migrations.CreateModel(
            name="ConfirmCode",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        max_length=31, verbose_name="Номер телефона"
                    ),
                ),
                ("code", models.TextField(max_length=50, verbose_name="Код проверки")),
                ("action", models.CharField(max_length=50, verbose_name="Действие")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время создания"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время создания"),
                ),
            ],
        ),
    ]
