# Generated by Django 3.1.6 on 2021-02-06 10:47

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        max_length=31, verbose_name="Номер телефона"
                    ),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Почта")),
                ("birth", models.DateField(verbose_name="Дата рождения")),
            ],
        ),
        migrations.CreateModel(
            name="FooterSocial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.CharField(max_length=255, verbose_name="Ссылка на соцсеть"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("instagram", "Инстаграмм"),
                            ("facebook", "Фейсбук"),
                            ("tiktok", "Тикток"),
                            ("yotube", "Ютуб"),
                            ("vk", "Вконтакте"),
                            ("google_play", "Google Play"),
                            ("app_store", "Apple Store"),
                        ],
                        max_length=255,
                        unique=True,
                        verbose_name="Соцсеть",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Имя заказчика"),
                ),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        max_length=31, verbose_name="Номер телефона"
                    ),
                ),
                ("address", models.TextField(max_length=150, verbose_name="Адрес")),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("cash", "Наличными"), ("card", "Картой на сайте")],
                        max_length=100,
                        verbose_name="Способ оплаты",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "article",
                    models.CharField(
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Артикул",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "price_discounted",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Цена после скидки",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("filling", models.TextField(verbose_name="Начинка")),
                ("topping", models.TextField(verbose_name="Декор")),
                (
                    "image",
                    models.FileField(
                        upload_to="upload/image/product/", verbose_name="Картинка"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Категория"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(default=1, verbose_name="Количество продукта"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="shop.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(default=1, verbose_name="Количество продукта"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.customer"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
        ),
    ]
