# Generated by Django 3.1.6 on 2021-02-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "price_discounted",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Цена после скидки",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("filling", models.TextField(verbose_name="Начинка")),
                ("topping", models.TextField(verbose_name="Декор")),
            ],
        ),
    ]
