# Generated by Django 3.1.6 on 2021-02-04 05:51

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        max_length=31, verbose_name="Номер телефона"
                    ),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Почта")),
                ("birth", models.DateField(verbose_name="Дата рождения")),
            ],
        ),
    ]
