# Generated by Django 3.1.6 on 2021-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="amount",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Доступное количество"
            ),
            preserve_default=False,
        ),
    ]
