# Generated by Django 3.1.7 on 2021-05-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_auto_20210514_2122"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="menu_position",
            field=models.PositiveIntegerField(default=1, verbose_name="Позиция в меню"),
            preserve_default=False,
        ),
    ]
