# Generated by Django 3.1.6 on 2021-02-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_order_orderproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSocial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.CharField(max_length=255, verbose_name="Ссылка на соцсеть"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("instagram", "Инстаграмм"),
                            ("facebook", "Фейсбук"),
                            ("tiktok", "Тикток"),
                            ("yotube", "Ютуб"),
                            ("vk", "Вконтакте"),
                            ("google_play", "Google Play"),
                            ("app_store", "Apple Store"),
                        ],
                        max_length=255,
                        unique=True,
                        verbose_name="Соцсеть",
                    ),
                ),
            ],
        ),
    ]
