# Generated by Django 3.1.7 on 2021-05-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_cakestandard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="menu_position",
            new_name="position",
        ),
    ]
