# Generated by Django 3.1.6 on 2021-02-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_auto_20210209_1957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="amount",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Количество продукта"
            ),
        ),
    ]
