# Generated by Django 3.1.6 on 2021-02-13 13:33

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_auto_20210210_1706"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "work_hours",
                    models.CharField(max_length=50, verbose_name="Время работы"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        blank=True,
                        max_length=31,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
            ],
        ),
    ]
