# Generated by Django 3.1.7 on 2021-05-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_auto_20210514_2155"),
    ]

    operations = [
        migrations.AddField(
            model_name="cakestandard",
            name="description",
            field=models.TextField(default="описание", verbose_name="Описание"),
            preserve_default=False,
        ),
    ]
