# Generated by Django 3.1.7 on 2021-05-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_cakestandard_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="cakedesign",
            name="category",
            field=models.CharField(
                default="Свадебные", max_length=100, verbose_name="Категория"
            ),
            preserve_default=False,
        ),
    ]
