# Generated by Django 3.1.6 on 2021-02-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_auto_20210207_0805"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="image/product/", verbose_name="Картинка"
            ),
        ),
    ]
