# Generated by Django 3.1.6 on 2021-02-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_address_contactnumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactnumber",
            old_name="phone",
            new_name="number",
        ),
    ]
