# Generated by Django 3.1.6 on 2021-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_auto_20210213_1341"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="recommendations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="_product_recommendations_+",
                to="shop.Product",
            ),
        ),
    ]
