# Generated by Django 3.1.7 on 2021-05-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_customcakedesignuploads"),
    ]

    operations = [
        migrations.AddField(
            model_name="customcakedesignuploads",
            name="name",
            field=models.CharField(
                db_index=True,
                default="any",
                max_length=100,
                verbose_name="название файла",
            ),
            preserve_default=False,
        ),
    ]
