# Generated by Django 3.1.6 on 2021-02-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_auto_20210213_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="recommendations",
            field=models.ManyToManyField(blank=True, to="shop.Product"),
        ),
    ]
