# Generated by Django 3.1.7 on 2021-05-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_customcakedesignuploads_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="address",
        ),
        migrations.AddField(
            model_name="useraddress",
            name="doorphone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Домофон"
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="entrance",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Подъезд"
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="floor",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Этаж"
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="house",
            field=models.CharField(default="", max_length=255, verbose_name="Дом"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraddress",
            name="room",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Квартира/офис"
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="street",
            field=models.CharField(default="", max_length=255, verbose_name="Улица"),
            preserve_default=False,
        ),
    ]
