# Generated by Django 3.1.6 on 2021-02-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_auto_20210213_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default="", max_length=50, verbose_name="Номер заказа"
            ),
            preserve_default=False,
        ),
    ]
