# Generated by Django 3.1.6 on 2021-02-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_auto_20210207_1000"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "image",
                    models.ImageField(
                        upload_to="image/product/", verbose_name="Картинка"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(max_length=50, verbose_name="Текст кнопки"),
                ),
                (
                    "button_url",
                    models.URLField(max_length=255, verbose_name="Ссылка на кноке"),
                ),
                ("order", models.SmallIntegerField(verbose_name="Порядок")),
            ],
        ),
    ]
