# Generated by Django 3.1.6 on 2021-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="button_url",
            field=models.CharField(max_length=255, verbose_name="Ссылка на кноке"),
        ),
    ]
