# Generated by Django 3.1.6 on 2021-02-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_order_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="category",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="article",
            field=models.CharField(default="", max_length=100, verbose_name="Артикул"),
            preserve_default=False,
        ),
    ]
