# Generated by Django 3.1.6 on 2021-02-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_orderproduct_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Адрес", "verbose_name_plural": "Адреса"},
        ),
        migrations.AlterModelOptions(
            name="banner",
            options={"verbose_name": "Баннер", "verbose_name_plural": "Баннеры"},
        ),
        migrations.AlterModelOptions(
            name="cartproduct",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="contactnumber",
            options={"verbose_name": "Телефон", "verbose_name_plural": "Телефоны"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="footersocial",
            options={"verbose_name": "Футер", "verbose_name_plural": "Футеры"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="orderproduct",
            options={
                "verbose_name": "Продукт из заказа",
                "verbose_name_plural": "Продукты из заказа",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Картинка продукта",
                "verbose_name_plural": "Картинки продуктов",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
        migrations.AlterModelOptions(
            name="promotedproductsmanual",
            options={
                "verbose_name": "Промо ручная настройка",
                "verbose_name_plural": "Промо ручная настройка",
            },
        ),
        migrations.AlterModelOptions(
            name="promotedproductssettings",
            options={
                "verbose_name": "Настройка промо",
                "verbose_name_plural": "Настройки промо",
            },
        ),
    ]
