# Generated by Django 3.1.6 on 2021-02-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_auto_20210219_1647"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footersocial",
            options={"verbose_name": "Соцсеть", "verbose_name_plural": "Соцсети"},
        ),
    ]
