# Generated by Django 3.1.7 on 2021-03-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_auto_20210219_1651"),
    ]

    operations = [
        migrations.CreateModel(
            name="CakeDesign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="image/cake/", verbose_name="Картинка"),
                ),
            ],
            options={
                "verbose_name": "Дизайн торта",
                "verbose_name_plural": "Дизайны торта",
            },
        ),
        migrations.CreateModel(
            name="CakeTopping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="image/cake/", verbose_name="Картинка"),
                ),
            ],
            options={
                "verbose_name": "Начинка торта",
                "verbose_name_plural": "Начинки торта",
            },
        ),
        migrations.AlterField(
            model_name="footersocial",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("instagram", "Инстаграмм"),
                    ("facebook", "Фейсбук"),
                    ("tiktok", "Тикток"),
                    ("youtube", "Ютуб"),
                    ("vk", "Вконтакте"),
                    ("google_play", "Google Play"),
                    ("app_store", "Apple Store"),
                ],
                max_length=255,
                unique=True,
                verbose_name="Соцсеть",
            ),
        ),
    ]
