# Generated by Django 3.1.7 on 2021-03-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_auto_20210310_0819"),
    ]

    operations = [
        migrations.CreateModel(
            name="CakeDecor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="image/cake/", verbose_name="Картинка"),
                ),
            ],
            options={
                "verbose_name": "Торт на заказ декор",
                "verbose_name_plural": "Торт на заказ (декор)",
            },
        ),
        migrations.CreateModel(
            name="CakePostcard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="image/cake/", verbose_name="Картинка"),
                ),
            ],
            options={
                "verbose_name": "Торт на заказ открытка",
                "verbose_name_plural": "Торт на заказ (открытка)",
            },
        ),
        migrations.AlterModelOptions(
            name="cakedesign",
            options={
                "verbose_name": "Торт на заказ дизайн",
                "verbose_name_plural": "Торт на заказ (дизайн)",
            },
        ),
        migrations.AlterModelOptions(
            name="caketopping",
            options={
                "verbose_name": "Торт на заказ начинка",
                "verbose_name_plural": "Торт на заказ (начинка)",
            },
        ),
    ]
