# Generated by Django 3.1.7 on 2021-03-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_auto_20210313_2036"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="iiko_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="ID IIKO",
            ),
        ),
    ]
