# Generated by Django 3.1.7 on 2021-03-18 17:11

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_product_iiko_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthCode",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        max_length=31, verbose_name="Номер телефона"
                    ),
                ),
                ("code", models.TextField(max_length=50, verbose_name="Код проверки")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время создания"),
                ),
            ],
        ),
    ]
