# Generated by Django 3.1.7 on 2021-03-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_authcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="button_text",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Текст кнопки"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="button_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ссылка на кноке"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Заголовок"
            ),
        ),
    ]
