# Generated by Django 3.1.7 on 2021-03-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_authcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authcode",
            name="id",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
