# Generated by Django 3.1.7 on 2021-03-23 05:56

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0026_user_birthday"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmCode",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        max_length=31, verbose_name="Номер телефона"
                    ),
                ),
                ("code", models.TextField(max_length=50, verbose_name="Код проверки")),
                ("action", models.CharField(max_length=50, verbose_name="Действие")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время создания"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AuthCode",
        ),
    ]
