# Generated by Django 3.1.7 on 2021-03-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0027_auto_20210323_0856"),
    ]

    operations = []
