# Generated by Django 3.1.7 on 2021-03-25 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0030_auto_20210324_2220"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Время создания"),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
